export const ErrorCodes = Object.freeze({
  STUDENT_NOT_FOUND:           { code: 'student_not_found',           status: 404 },
  REVIEW_NOT_FOUND:            { code: 'review_not_found',            status: 404 },
  COURSE_NOT_FOUND:            { code: 'course_not_found',            status: 404 },
  ASPECT_NOT_FOUND:            { code: 'aspect_not_found',            status: 404 },
  SECTION_NOT_FOUND:           { code: 'section_not_found',           status: 404 },
  SUBJECT_NOT_FOUND:           { code: 'subject_not_found',           status: 404 },
  TEACHER_NOT_FOUND:           { code: 'teacher_not_found',           status: 404 },
  TRY_NOT_FOUND:               { code: 'try_not_found',               status: 404 },
  REVIEW_ALREADY_EXISTS:       { code: 'review_already_exists',       status: 409 },
  TRY_ALREADY_EXISTS:          { code: 'try_already_exists',          status: 409 },
  USER_ALREADY_ACTIVE:         { code: 'user_already_active',         status: 409 },
  AUTH_TOKEN_MISSING:          { code: 'auth_token_missing',          status: 401 },
  AUTH_TOKEN_INVALID:          { code: 'auth_token_invalid',          status: 401 },
  AUTH_TOKEN_EXPIRED:          { code: 'auth_token_expired',          status: 401 },
  AUTH_INVALID_CREDENTIALS:    { code: 'auth_invalid_credentials',    status: 401 },
  AUTH_CARRERA_NOT_ENROLLED:   { code: 'auth_carrera_not_enrolled',   status: 401 },
  VALIDATION_ERROR:            { code: 'validation_error',            status: 400 },
  INTERNAL_ERROR:              { code: 'internal_error',              status: 500 },
  INSUFFICIENT_PERMISSIONS:    { code: 'insufficient_permissions',    status: 403 },
  DUPLICATE_ENTRY:             { code: 'duplicate_entry',             status: 409 },
  TOKEN_INVALID:               { code: 'token_invalid',               status: 400 },
  TOKEN_EXPIRED:               { code: 'token_expired',               status: 400 },
  INVALID_EMAIL_DOMAIN:        { code: 'invalid_email_domain',        status: 400 },
  CAREER_NOT_FOUND:            { code: 'career_not_found',            status: 404 },
  CAREER_LIMIT_EXCEEDED:       { code: 'career_limit_exceeded',       status: 400 },
  STUDENT_ALREADY_EXISTS:      { code: 'student_already_exists',      status: 409 },
});
