export const permissionsMap = Object.freeze({
  ADMIN: [
    'student:read', 'student:write',
    'subject:read',
    'teacher:read',
    'course:read',
    'section:read',
    'review:access', 'review:read:all', 'review:write', 'review:update', 'review:delete',
    'try:access', 'try:read:all', 'try:write', 'try:update', 'try:delete',
    'profile:read',
    'career:bypass_enrollment',
  ],
  STUDENT: [
    'course:read',
    'subject:read',
    'teacher:read',
    'section:read',
    'review:access', 'review:write', 'review:update', 'review:delete',
    'try:access', 'try:write', 'try:update', 'try:delete',
    'profile:read',
  ],
  GUEST: [
    'course:read',
    'subject:read',
    'teacher:read',
    'section:read',
    'review:access',
    'try:access',
  ],
  INACTIVE: [],
});
